
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/user/AppData/Local/Programs/CLion Nova/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
